baseurl = "https://machinegurning.com/"
languageCode = "en-gb"
title = "MachineGurning.com"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    rstats = "/:section/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/machinegurning"
[[menu.main]]
    name = "Matt Upson"
    url = "https://twitter.com/m_a_upson"
[[menu.main]]
    name = "Matt Gregory"
    url = "https://twitter.com/mammykins_"

[params]
    description = "A blog about Data Science, Statistics, IoT, Machine Learning, and Artificial Intelligence."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "https://cdnjs.cloudflare.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "https://cdnjs.cloudflare.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "default-thumb.png"
    width = 50
    height = 50
    alt = "MachineGurning Logo"

